"""empty message

Revision ID: 0e3c53074979
Revises: 95bc8b4bc3cd
Create Date: 2023-04-04 09:25:41.716199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3c53074979'
down_revision = '95bc8b4bc3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_modelid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_booking_email_user'), 'user', ['email'], ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_booking_car_modelid_car'), 'car', ['car_modelid'], ['car_modelid'])
        batch_op.drop_column('car_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_booking_car_modelid_car'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_booking_email_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'car', ['car_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('car_modelid')

    # ### end Alembic commands ###
