"""empty message

Revision ID: 3508b45ea4f9
Revises: 4815aa004b46
Create Date: 2023-04-01 20:54:36.685061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3508b45ea4f9'
down_revision = '4815aa004b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('eir_code', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_car_eir_code_location'), 'location', ['eir_code'], ['eir_code'])
        batch_op.drop_column('location_Id')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_location_eir_code'), ['eir_code'])
        batch_op.drop_column('id')

    #### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_location_eir_code'), type_='unique')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_Id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_car_eir_code_location'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['location_Id'], ['id'])
        batch_op.drop_column('eir_code')
        batch_op.drop_column('img')
        batch_op.drop_column('img_id')

    # ### end Alembic commands ###
