"""empty message

Revision ID: 4815aa004b46
Revises: f3f5a4e87234
Create Date: 2023-03-19 12:35:54.589239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4815aa004b46'
down_revision = 'f3f5a4e87234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('drivers_license', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('drivers_license')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
