"""Initial migration.

Revision ID: 6a3ac4ac304e
Revises: 
Create Date: 2023-03-07 17:07:27.563813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3ac4ac304e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('booking_from_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('booking_to_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('car_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('car_price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location_Id', sa.Integer(), nullable=True))
        batch_op.alter_column('car_modelid',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('car_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('car_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'location', ['location_Id'], ['id'])
        batch_op.drop_column('car_features')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('contact',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('dob')

    # ### end Alembic commands ###