"""empty message

Revision ID: 811c6e829506
Revises: 3508b45ea4f9
Create Date: 2023-04-02 03:14:09.147527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c6e829506'
down_revision = '3508b45ea4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('car_modelid',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('car_name',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('car_no',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('eir_code',
               existing_type=sa.TEXT(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('eir_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
        batch_op.alter_column('car_no',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=False)
        batch_op.alter_column('car_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('car_modelid',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
