"""empty message

Revision ID: 95bc8b4bc3cd
Revises: 811c6e829506
Create Date: 2023-04-02 12:17:03.082826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bc8b4bc3cd'
down_revision = '811c6e829506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.String(length=50), nullable=False))
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
